using System;
using System.Reflection;
using System.CodeDom.Compiler;

namespace Evaluator
{
	/// <summary>
	/// Wraps the results of a programmatically-accessed compilation with the warnings generated by the compiler.
	/// </summary>
	public class AssemblyResults
	{
		Assembly assembly;
		CompilerErrorCollection warnings;

		/// <summary>
		/// Gets the <see cref="Type"/> object that represents the specified type from the compiled assembly. <seealso cref="Assembly.GetType"/>
		/// </summary>
		/// <param name="type