using System;
using System.Reflection;
using System.CodeDom.Compiler;

namespace Evaluator
{
	/// <summary>
	/// Wraps the results of a programmatically-accessed compilation with the warnings generated by the compiler.
	/// </summary>
	public class AssemblyResults
	{
		Assembly assembly;
		CompilerErrorCollection warnings;

		/// <su