using System;
using System.Reflection;
using System.Reflection.Emit;
using System.CodeDom.Compiler;

using Microsoft.CSharp;

namespace Evaluator
{
	/// <summary>
	/// Wraps the results of a programmatically-accessed compilation of a method with the warnings generated by the compiler.
	/// </summary>
	public class MethodResults
	{
		MethodInf